name: Merge upstream branches
on:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  Merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name ${{ secrets.USER_NAME }}
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git pull --unshallow
          git remote add upstream https://github.com/FBlackBox/BlackBox.git
          git fetch upstream
          git checkout master
          git merge --no-edit upstream/master
          git push origin master

